version: '2'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - WRONG_HOST=www.youwatana.be
      - TRUES_HOST=youwatana.be
    command: /bin/bash -c "envsubst '$$WRONG_HOST$$TRUES_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
